server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/reservations/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
