server:
  port: 8086

spring:
  application:
    name: resilience-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      resilienceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      resilienceRetry:
        maxAttempts: 3
        waitDuration: 2s

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
