server:
  port: 8085

spring:
  application:
    name: monitoring-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
